baseURL = 'http://localhost:1313/'
languageCode = 'ms-my'
title = 'Dadih YangTu - Dadih Susu Berkrim & Berlemak'

[params]
  description = "Dadih susu asli paling berkrim dan berlemak di Permatang Pauh dan sekitar Seberang Perai, Penang. Pilihan utama untuk jamuan, kenduri, dan infak. Tempah online sekarang!"
  # YOUR WHATSAPP LINK HERE
  whatsapp_link = "https://is.gd/DadihYangTu" 
  phone_display = "013-766 2785"
  location = "Residensi Pauh Permai, Permatang Pauh, Penang"
